window.WORDRA_DATA = window.WORDRA_DATA || {};
window.WORDRA_DATA.WORDS = [
"APPLE","BEACH","BRAIN","BRAVE","CHAIR","CLOUD","DANCE","DREAM","EAGLE","EARTH",
"EQUAL","EXACT","FAMILY","FLAME","FLOWER","FRUIT","GIANT","GLASS","GREEN","HEART",
"HOUSE","IMAGE","LIGHT","MAGIC","MONEY","MUSIC","NIGHT","OCEAN","ORBIT","PAPER",
"PEACE","PLANET","POWER","QUEEN","QUICK","RIVER","ROBOT","ROUND","SCHOOL","SHAPE",
"SMILE","SPACE","SPEED","STAR","STONE","STORY","SUNNY","TABLE","TIGER","TRAIN",
"TREE","WATER","WORLD","YOUNG","ZEBRA","DOZEN","RELAX","LEARN","WRITE","BUILD",
"SHEEP","QUITE","GHOST","HOUSE","GREEN","HEART","MUSIC","LIGHT","DREAM","EARTH",
"TRAIN","CLOUD","PLANT","STONE","BRAVE","QUIET","SMART","READY","SWEET","RIVER"
];

window.WORDRA_DATA.BONUS = [
"ACE","AIR","ALL","ANT","ART","ATE","BAR","BAT","BED","BIG","CAN","CAR","CAT","DAY",
"DOG","EAR","EAT","END","EYE","FAR","FIRE","FUN","GAS","HAT","ICE","KEY","KID","MAP",
"MAN","MAY","MEN","MOON","NET","ONE","OPEN","RED","SEA","SIT","SKY","SUN","TOP","TWO",
"USE","WAY","WIN","WORD","WORLD","STAR","TREE","WATER","HOUSE","LIGHT","HEART","BRAIN"
];

